version: '3.8'

services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      # Add any other environment variables your app needs
    restart: unless-stopped
    # If you need to connect to other services like a database, add them here
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
